### ISSUE TITLE
Crashing after yesterdays update

### ISSUE THREAD

**Issue by Tyler12345556** [flashyyxd/Narcissisti.cc#2]
So i use Narcissisti.cc as my base and I really like it... yesterday it broke with everyother cheat how can i fix this, can someone post a fixed vers, i really dont want to but i would even pay alittle for it bc i need it as my base and im very very happy with this cheat... please someone help

**Comment by Tyler12345556** [comment]
not even need a fixed vers but can someone show me where i need to fix stuff

**Comment by outlassn** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/228322-cs-update-2017-08-18t-spoonfeed-thread.html

**Comment by flashyyxd** [comment]
Thanks, @outlassn
